id: I5D48AD4A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:48:22+00:00'
last_modified: '2022-06-07T22:25:57.229650+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03846
  title: གསུང་འབུམ། བློ་དགའ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    099C:
      image_group_id: I00KG03876
      title: ''
      total_pages: 2
      order: 1
      base_file: 099C.txt
    BDD2:
      image_group_id: I00KG03877
      title: ''
      total_pages: 2
      order: 2
      base_file: BDD2.txt
    DF97:
      image_group_id: I00KG03878
      title: ''
      total_pages: 658
      order: 3
      base_file: DF97.txt
    713F:
      image_group_id: I00KG03879
      title: ''
      total_pages: 2
      order: 4
      base_file: 713F.txt
    9DD3:
      image_group_id: I00KG03880
      title: ''
      total_pages: 2
      order: 5
      base_file: 9DD3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
